HIMACS_SchedulerUI/Models/ErrorViewModel.cs
using System;

namespace HIMACS_SchedulerUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HIMACS_SchedulerUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HIMACS_SchedulerUI.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;
using HIMACSSchedulerBusinessTier;

namespace HIMACS_SchedulerUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HIMACS_SchedulerUI/Controllers/JobHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HIMACSScheduleDataTier;
using HIMACSSchedulerBusinessTier;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace HIMACS_SchedulerUI.Controllers
{
    public class JobHistoryController : Controller
    {

        public IEnumerable<Job> Jobs;
        public IEnumerable<JobHistory> jobHistory;
        private void BindJobModel()
        {
            Jobs = HIMACSScheduleEngineBO.GetJobs();
        }
        public IActionResult Index()
        {
            BindJobModel();
            return View(Jobs);
        }
        public IActionResult Details(int id)
        {
            jobHistory = HIMACSScheduleEngineBO.Get_JobHistory(id);
            ViewData["JobName"] =  HIMACSScheduleEngineDO.JobNameById(id).Rows[0]["Name"].ToString();
            return View(jobHistory);
        }
    }
}

HIMACS_SchedulerUI/Controllers/JobScheduleMonitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HIMACSScheduleDataTier;
using HIMACSSchedulerBusinessTier;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace HIMACS_SchedulerUI.Controllers
{
    public class JobScheduleMonitorController : Controller
    {
        public IEnumerable<Job> Jobs;
        public IEnumerable<JobHistory> jobHistory;
        private void BindJobModel()
        {
            Jobs = HIMACSScheduleEngineBO.GetJobs();
        }
        public IActionResult Index()
        {
            BindJobModel();
            return View(Jobs);
        }

        public IActionResult Details(int id)
        {
            IEnumerable<JobSchedule> jobschedule = HIMACSScheduleEngineBO.GetJobSchedule(id);
            ViewData["JobName"] = HIMACSScheduleEngineDO.JobNameById(id).Rows[0]["Name"].ToString();
            return View(jobschedule);
        }
    }
}

HIMACS_SchedulerUI/Controllers/JobSpecificConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HIMACSSchedulerBusinessTier;
using Microsoft.AspNetCore.Mvc;
using Models;
using HIMACSScheduleDataTier;

namespace HIMACS_SchedulerUI.Controllers
{
    public class JobSpecificConfigController : Controller
    {
        public IEnumerable<Job> Jobs;
        public IEnumerable<JobHistory> jobHistory;
        private void BindJobModel()
        {
            Jobs = HIMACSScheduleEngineBO.GetJobs();
        }
        public IActionResult Index()
        {
            BindJobModel();
            return View(Jobs);
        }

        public IActionResult Details(int id)
        {
            IEnumerable<JobSpecificConfig> jobSpecific = HIMACSScheduleEngineBO.GetJobSpecificConfig(id);
            ViewData["JobName"] = HIMACSScheduleEngineDO.JobNameById(id).Rows[0]["Name"].ToString();
            return View(jobSpecific);
        }

        public IActionResult Edit(int id, string key)
        {
            JobSpecificConfig jobSpecific = HIMACSScheduleEngineBO.GetJobSpecificConfigByIDAndKey(id, key);
            return View(jobSpecific);
        }
        [HttpPost]
        public IActionResult Edit(JobSpecificConfig jobspecific)
        {
            HIMACSScheduleEngineBO.UpdateJobSpecificConfigByIDAndKey(jobspecific);

            IEnumerable<JobSpecificConfig> jobSpecific = HIMACSScheduleEngineBO.GetJobSpecificConfig(jobspecific.JobId);
            ViewData["JobName"] = HIMACSScheduleEngineDO.JobNameById(jobspecific.JobId).Rows[0]["Name"].ToString();
            return View("Details",jobSpecific);
        }

    }
}

HIMACS_SchedulerUI/Controllers/MaintainJobScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HIMACSScheduleDataTier;
using HIMACSSchedulerBusinessTier;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace HIMACS_SchedulerUI.Controllers
{
    public class MaintainJobScheduleController : Controller
    {
        public IEnumerable<Job> Jobs;
        public IEnumerable<JobHistory> jobHistory;
        private void BindJobModel()
        {
            Jobs = HIMACSScheduleEngineBO.GetJobs();
        }
        public IActionResult Index()
        {
            BindJobModel();
            return View(Jobs);
        }
        public IActionResult List(int id)
        {
            IEnumerable<JobSchedule> jobschedule = HIMACSScheduleEngineBO.GetJobSchedule(id);
            ViewData["JobName"] = HIMACSScheduleEngineDO.JobNameById(id).Rows[0]["Name"].ToString();
            return View(jobschedule);
        }
        public IActionResult Edit(int id)
        {
            JobSchedule jobschedule = HIMACSScheduleEngineBO.GetOneJobSchedule(id);
            ViewData["JobName"] = HIMACSScheduleEngineDO.JobNameById(id).Rows[0]["Name"].ToString();
            return View(jobschedule);
        }

        [HttpPost]
        public IActionResult Edit(JobSchedule schedul)
        {
            HIMACSScheduleEngineDO.UpdateRunStatusAndNextRunOnCompletion(schedul.Jobid, schedul.Status,Convert.ToDateTime(schedul.NextRunDate));
            BindJobModel();
            return View("Index",Jobs);
        }

        public IActionResult Delete(int id)
        {
            IEnumerable<JobSchedule> jobschedule = HIMACSScheduleEngineBO.GetJobSchedule(id);
            ViewData["JobName"] = HIMACSScheduleEngineDO.JobNameById(id).Rows[0]["Name"].ToString();
            return View(jobschedule);
        }
    }
}

HIMACS_SchedulerUI/Controllers/PipelineConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HIMACSSchedulerBusinessTier;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace HIMACS_SchedulerUI.Controllers
{
    public class PipelineConfigController : Controller
    {
        public IEnumerable<Job> Jobs;
        public IEnumerable<JobHistory> jobHistory;
        private void BindJobModel()
        {
            Jobs = HIMACSScheduleEngineBO.GetJobs();
        }
        public IActionResult Index()
        {
            BindJobModel();
            return View(Jobs);
        }
        public IActionResult Edit(int jobId)
        {
            PipelineConfig config = HIMACSScheduleEngineBO.GetPipelineConfigAsConfigObject(jobId);
            return View(config);
        }

        [HttpPost]
        public IActionResult Edit(PipelineConfig config)
        {
            HIMACSScheduleEngineBO.UpdatePipelineConfig(config);
            BindJobModel();
            return View("Index",Jobs);
        }
    }
}

HIMACS_SchedulerUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <br />
    <br />
    <br />
    <br />
    <h1 class="display-4">Welcome to Himacs Scheduler</h1>
</div>

HIMACS_SchedulerUI/Views/JobHistory/Details.cshtml
@model IEnumerable<Models.JobHistory>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Job History for @ViewData["JobName"]</h1>

<p>

</p>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.JobId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTime)
                </td>
            </tr>
        }
    </tbody>
</table>

HIMACS_SchedulerUI/Views/JobHistory/Index.cshtml
@model IEnumerable<Models.Job>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h1>Job History</h1>
<br />
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (Models.Job item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JobId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobName)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.JobId })
            </td>
        </tr>
}
    </tbody>
</table>

HIMACS_SchedulerUI/Views/JobScheduleMonitor/Details.cshtml
@model IEnumerable<Models.JobSchedule>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Jobid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Schedule)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Job)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NextRunDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Jobid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Schedule)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Job)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NextRunDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            </tr>
        }
    </tbody>
</table>

HIMACS_SchedulerUI/Views/JobScheduleMonitor/Index.cshtml
@model IEnumerable<Models.Job>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h1>Job Schedule Monitor</h1>
<br />
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Models.Job item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.JobId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobName)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.JobId })
                </td>
            </tr>
        }
    </tbody>
</table>

HIMACS_SchedulerUI/Views/JobSpecificConfig/Details.cshtml
@model IEnumerable<Models.JobSpecificConfig>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Key)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.JobId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.JobId, key = item.Key })
                </td>
            </tr>
        }
    </tbody>
</table>

HIMACS_SchedulerUI/Views/JobSpecificConfig/Edit.cshtml
@model Models.JobSpecificConfig

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>JobSpecificConfig</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <input asp-for="JobId" class="form-control" />
                <span asp-validation-for="JobId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Key" class="control-label"></label>
                <input asp-for="Key" class="form-control"  />
                <span asp-validation-for="Key" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

HIMACS_SchedulerUI/Views/JobSpecificConfig/Index.cshtml
@model IEnumerable<Models.Job>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h1>Job Specific Config</h1>
<br />
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Models.Job item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.JobId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobName)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.JobId })
                </td>
            </tr>
        }
    </tbody>
</table>

HIMACS_SchedulerUI/Views/MaintainJobSchedule/Edit.cshtml
@model Models.JobSchedule

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>JobSchedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Jobid" class="control-label"></label>
                <input asp-for="Jobid" class="form-control" />
                <span asp-validation-for="Jobid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Schedule" class="control-label"></label>
                <input asp-for="Schedule" class="form-control" />
                <span asp-validation-for="Schedule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job" class="control-label"></label>
                <input asp-for="Job" class="form-control" />
                <span asp-validation-for="Job" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NextRunDate" class="control-label"></label>
                <label>{format : MM/dd/yyyy HH:mm }</label>
                <input asp-for="NextRunDate" class="form-control" />
                <span asp-validation-for="NextRunDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <label>{NOT_STARTED, RUNNING, IDLE, IDLE WITH EXCEPTION}</label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

HIMACS_SchedulerUI/Views/MaintainJobSchedule/Index.cshtml
@model IEnumerable<Models.Job>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h1>Maintain Job Schedule</h1>
<br />
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Models.Job item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.JobId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobName)
                </td>
                <td>
                    @Html.ActionLink("List", "List", new { id = item.JobId })
                </td>
            </tr>
        }
    </tbody>
</table>

HIMACS_SchedulerUI/Views/MaintainJobSchedule/List.cshtml
@model IEnumerable<Models.JobSchedule>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List</h1>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Jobid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Schedule)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Job)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NextRunDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Jobid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Schedule)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Job)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NextRunDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Jobid })
                </td>
            </tr>
        }
    </tbody>
</table>

HIMACS_SchedulerUI/Views/PipelineConfig/Edit.cshtml
@model Models.PipelineConfig

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>PipelineConfig</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <input asp-for="JobId" class="form-control" />
                <span asp-validation-for="JobId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenantID" class="control-label"></label>
                <input asp-for="TenantID" class="form-control" />
                <span asp-validation-for="TenantID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationId" class="control-label"></label>
                <input asp-for="ApplicationId" class="form-control" />
                <span asp-validation-for="ApplicationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthenticationKey" class="control-label"></label>
                <input asp-for="AuthenticationKey" class="form-control" />
                <span asp-validation-for="AuthenticationKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubscriptionId" class="control-label"></label>
                <input asp-for="SubscriptionId" class="form-control" />
                <span asp-validation-for="SubscriptionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResourceGroup" class="control-label"></label>
                <input asp-for="ResourceGroup" class="form-control" />
                <span asp-validation-for="ResourceGroup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFactoryName" class="control-label"></label>
                <input asp-for="DataFactoryName" class="form-control" />
                <span asp-validation-for="DataFactoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PipelineName" class="control-label"></label>
                <input asp-for="PipelineName" class="form-control" />
                <span asp-validation-for="PipelineName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

HIMACS_SchedulerUI/Views/PipelineConfig/Index.cshtml
@model IEnumerable<Models.Job>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h1>Pipeline Config</h1>
<br />
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Models.Job item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.JobId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { jobId = item.JobId })
                </td>
            </tr>
        }
    </tbody>
</table>

HIMACS_SchedulerUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HIMACS_SchedulerUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HIMACS SchedulerUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <form class="form-inline my-2 my-lg-0">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Options
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                <a class="dropdown-item" asp-area="" asp-controller="JobHistory" asp-action="Index">Job History</a>
                                <a class="dropdown-item" asp-area="" asp-controller="JobScheduleMonitor" asp-action="Index">Job Schedule Monitor</a>
                                <a class="dropdown-item" asp-area="" asp-controller="MaintainJobSchedule" asp-action="Index">Maintain Job Schedule</a>
                                <a class="dropdown-item" asp-area="" asp-controller="PipelineConfig" asp-action="Index">Pipeline Config</a>
                                <a class="dropdown-item" asp-area="" asp-controller="JobSpecificConfig" asp-action="Index">Job Specific Config</a>
                            </div>
                        </li>
                    </ul>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HIMACS_SchedulerUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>